pyodide/pytest-pyodide

- .github/workflows/main.yml
- README.md
- pyproject.toml
- pytest_pyodide/__init__.py
- setup.cfg
- Adds minimal "how to use" description in the readme (closes #6 )
- Enables setuptools_scm to get the version from the git tag. For release one only need to tag (there is no need to manually specify version). 
- Add CI setup to publish to PyPI. @ryanking13 please remind me your PyPI username, I'll add to there. 
For now, I just uploaded a test version to make sure the rendering is OK https://pypi.org/project/pytest-pyodide/. 
I'm not really sure what we should do about versions:
a) either we make the versioning be completely independent and start say with 0.1.0
b) or we try to follow Pyodide versions but then it means we can't easily use semver
In any case, version x of this package would likely work only with some range of pyodide versions (at least those that we check in CI).
> Publish to PyPI

- pytest_pyodide/hook.py
- tests/test_marker.py
Migrates `xfail_browsers` marker from the [Pyodide main repository](https://github.com/pyodide/pyodide/blob/e673fde7cfda83fb63ac998708cc07b8d6fd77b0/conftest.py#L128-L163)
> Handle xfail_browsers marker

- pytest_pyodide/decorator.py
- setup.cfg
This is paired with https://github.com/pyodide/pyodide/pull/2944. 
It uses a fork of tblib with this patch:
https://github.com/ionelmc/python-tblib/pull/66
Consider the following test:
```py
@run_in_pyodide
def test_blah(selenium):
def f():
raise Exception("hi!")
f()
```
Before this PR:
```py
pytest-pyodide/pytest_pyodide/decorator.py:99: in test_blah
run_test(selenium_arg_name, (arg1, arg2, ...))
pytest-pyodide/pytest_pyodide/decorator.py:226: in _run_test
raise result
<exec>:13: in __tmp
???
src/tests/test_file:5: in test_blah
f()
src/tests/test_file:4: in f
raise Exception("hi!")
E   Exception: hi!
```
After this PR:
```py
src/tests/test_file:5: in test_blah
f()
src/tests/test_file:4: in f
raise Exception("hi!")
E   Exception: hi!
```
> Use forked tblib and clean up tracebacks

- .github/workflows/main.yml
- CHANGELOG.md
- pytest_pyodide/__init__.py
- pytest_pyodide/fixture.py
- pytest_pyodide/hook.py
- pytest_pyodide/runner.py
- pytest_pyodide/server.py
- tests/test_decorator.py
- tests/test_marker.py
Adds safari runner for selenium, mostly adopted from @rth's PR in Pyodide https://github.com/pyodide/pyodide/pull/2578
I also added `selenium_standalone_refresh` fixture which I experimented in https://github.com/pyodide/pyodide/pull/2957.
Since selenium allows only one Safari browser instance active at any given time, the original `selenium_standalone` is not very suitable for Safari test.
I am not sure whether we should fully replace `selenium_standalone` with `selenium_standalone_refresh`, as it is not tested very much yet. So I made a separate fixture and add an option (`STANDALONE_REFRESH` env variable) which dynamically overrides `selenium_standalone` with `selenium_standalone_refresh`. I am open to better ideas.
> Add Safari runner for selenium

- .github/workflows/main.yml
- CHANGELOG.md
- README.md
- pytest_pyodide/hook.py
This is also adapted from https://github.com/pyodide/pyodide/pull/2578, I found that there are some more "standalone" fixtures that needs to be handled...
> Re-order safari test order to make sure only one session exists during the test

- .github/workflows/main.yml
- CHANGELOG.md
- README.md
- pytest_pyodide/hook.py
- tests/test_testing.py
Close #32 
The changes that I made in this PR are:
1. Run host tests by default, unless `-no-host` is given (e.g. `chrome-no-host`, `firefox-no-host`).
2. Remove the option `all` and support passing list of runtimes. (e.g. `--rt chrome --rt firefox`)
- I found that the option `all` was acutally not working correctly.
> Run host tests by default

- CHANGELOG.md
- pytest_pyodide/decorator.py
- tests/test_decorator.py
When you use a package/module in your pyodide tests which is not available in your host environment you get a `ModuleNotFoundError` exception. It is not trivial from the exception nor the traceback why this exception happened.
In this PR I added some more explanation when this exception happens and tell the user why it happened.
> Better explain what it means when you get a ModuleNotFound error

- CHANGELOG.md
- README.md
- pytest_pyodide/_decorator_in_pyodide.py
- pytest_pyodide/decorator.py
- pytest_pyodide/runner.py
- tests/test_decorator.py
@ryanking13 ran into the problem in https://github.com/pyodide/pyodide/pull/3184#discussion_r995293100 that it's inconvenient to send results from one `@run_in_pyodide` invocation to another. This adds a mechanism to do so. A `SeleniumHandle` (perhaps can be named better) can be returned to the host and when passed back into another `@run_in_pyodide` function one can use it to access the object.
This should allow us to make fixtures specifically for use with `@run_in_pyodide` functions that return one or more `SeleniumHandle`s.
> Add Pyodide handles

- CHANGELOG.md
- README.md
- pytest_pyodide/_decorator_in_pyodide.py
- pytest_pyodide/decorator.py
- tests/test_decorator.py
It turns out that the way I wrote PyodideHandle is pretty annoying to use. See for instance in https://github.com/pyodide/pyodide/pull/3184. This makes it unpickle to the actual object so it doesn't look so awkward. In particular, this way only the fixture has to bother with the `PyodideHandle` stuff. The consuming tests can act like it is a perfectly normal argument.
> Unpickle PyodideHandle into actual Pyodide object

- .github/workflows/build.yaml
- .github/workflows/filtermatrix.py
- .github/workflows/main.yaml
- .github/workflows/testall.yaml
Latest runners of GHA comes with Python 3.11 (macos-latest) or it does not support installing Python 3.10.2 with `setup-python` actions (ubuntu-latest).
> CI Pin OS versions

- .github/workflows/filtermatrix.py
- .github/workflows/main.yaml
- .github/workflows/testall.yaml
- CHANGELOG.md
- pytest_pyodide/fixture.py
- tests/test_fixture.py
I introduced `STANDALONE_REFRESH` env variable in order to test `selenium_standalone_refresh` fixture in https://github.com/pyodide/pyodide/pull/2578, but it is not used anymore. This PR removes it.
I added a test for `selenium_standalone_refresh` fixture that runs every time instead.
> Remove STANDALONE_REFRESH env variable

- .github/workflows/build.yaml
- .github/workflows/main.yaml
- .github/workflows/testall.yaml
- setup.cfg
I think this is how one should get rid of the self-build parameter (see https://github.com/pyodide/pytest-pyodide/pull/67 )
There's one check which is if the package includes pytest-pyodide it uninstalls the pip version, other than that it does pretty much the same for pytest-pyodide and other projects.
> Remove self build

- .github/workflows/filtermatrix.py
- .github/workflows/main.yaml
- CHANGELOG.md
This is a minor update:
a) adds support for changing python version based on pyodide version once pyodide upgrades to 3.11
b) changes ubuntu-latest to ubuntu-20.04 if you try to test something using python 3.10.2 with ubuntu-latest
I know the OS version has been explicitly fixed in pytest github, but it was breaking my CI builds where I'd got ubuntu-latest pointing at this action. Once more than one version of pyodide is supported, we'll need part (a) anyway, and I think part (b) is worth having also, as people shouldn't have to know about which versions of ubuntu are correct for which pyodide version.
> Auto-select python and runner versions

- .github/workflows/filtermatrix.py
- conftest.py
- tests/test_options.py
This adds tests for plugin cmdline options `--dist-dir`, `--runner`, `--runtime`, while removing a test-config that makes #59 fail.
> Add tests for plugin commandline options

- .github/codecov.yml
Otherwise when you do the big mega-build codecov reports low numbers because e.g. it reports back before playwright builds have finished.
I think this is pretty straightforward, but I wasn't sure if there was a reason this setting was turned on?
> make codecov wait for ci to finish before reporting

- .github/workflows/filtermatrix.py
- CHANGELOG.md
- README.md
It would probably be good to make a new release. 
Closes #50 
I added the compatibility table between pytest-pyodide and Pyodide to the Readme and updated CI to test Pyodide 0.22.0
I would still be more comfortable if the version of this package wasn't closely following Pyodide version, while being completely unrelated. At the same time, the only thing we could do to avoid it is to make 1.0.0 release, which is probably still a bit early.
cc @ryanking13 @joemarshall
> Version 0.50

- .github/workflows/build.yaml
- .pre-commit-config.yaml
- pyproject.toml
- pytest_pyodide/decorator.py
- pytest_pyodide/hook.py
- pytest_pyodide/server.py
Replace iosrt, pycln, pyupgrade, and flake8 with ruff as we do in other repositories.
This PR also removes GHA linter job, in favor of pre-commit.ci.
> CI Use ruff + remove GHA lint job

- pytest_pyodide/fixture.py
- pytest_pyodide/runner.py
So that we can add extra flags to the runtimes if we need to.
Used in https://github.com/pyodide/pyodide/pull/3210
> Add CHROME_FLAGS, FIREFOX_FLAGS, and NODE_FLAGS

- pytest_pyodide/runner.py
executable_path has been deprecated since Selenium v4.0.0b1 and is removed in v4.10. Remove it.
https://github.com/SeleniumHQ/selenium/blob/d6acda7c0254f9681574bf4078ff2001705bf940/py/CHANGES#L101
> Remove executable_path from selenium driver construction

- pytest_pyodide/fixture.py
- tests/test_fixture.py
Previously both chrome and firefox playwright runtimes were launched even if we use only one of them. This changes it to only launch requested runtimes.
> playwright: launch only requested runtimes

- pytest_pyodide/fixture.py
- pytest_pyodide/hook.py
- tests/test_fixture.py
We use a bunch of different selenium variants but for the most part they are drop-in replacements for each other. For instance, when using `selenium_standalone`, we always just say `selenium = selenium_standalone` at the top of the function. I think it's clearer if we use a decorator to rename the fixture.
> ENH Add rename_fixture and standalone decorators

- .github/workflows/main.yaml
Use pyodide-actions@v1 so that an update in pyodide-actions can be applied without modification in pytest-pyodide.
It is interesting that [the recommended way of versioning github actions is moving tags](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md)... so we need to force push to v1 tag whenever we make an update to pyodide-actions.
> Use pyodide-actions@v1

- .github/workflows/main.yaml
- pytest_pyodide/runner.py
This fixes a regression introduced in Selenium 4.11.
From Selenium 4.11, if we pass a binary name to `Service`, it will not search the binary from PATH, but it will use it as a relative path and search the binary from cwd instead (I think it is a bug).
This PR fixes it by not passing the binary name, so that letting selenium locate the binary from PATH.
Related PR: https://github.com/SeleniumHQ/selenium/pull/12356
> Fix selenium can't find FireFox driver

- pytest_pyodide/hook.py
- tests/test_options.py
This fixes a test failure that started to occur after #101.
```
! _pytest.outcomes.Exit: playwright failed to launch
```
The cause of the problem was that the combination of the `pytester` fixture and the `pytest_configure` hook is not very good.
We use `pytest_configure` to manage global settings, but this function is called again when we run sub-tests using pytester, resulting in new global settings being overwritten.
So I added a check to prevent overwriting global settings once it is set.
> Prevent from overwriting global configurations

- .github/workflows/build.yaml
- .github/workflows/main.yaml
- CHANGELOG.md
- COMPATIBILITY.md
- README.md
- pytest_pyodide/node_test_driver.js
- pytest_pyodide/runner.py
- utils/build_test_matrix.py
Drops node < v18 support from pytest-pyodide. Also update tested Pyodide versions.
> Drop node < v18 support

- pytest_pyodide/_decorator_in_pyodide.py
- tests/test_decorator.py
Fixes a shortcoming encountered by @szabolcsdombi in https://github.com/pyodide/pyodide/pull/4208.
pytest sets `__module__` to `builtins`. This puts back the correct value.
> Add support for `pytest.skip` etc inside of `@run_in_pyodide`

- pytest_pyodide/runner.py
This PR adds a fixture `use_global_safari_service`. It makes safari runner to use a pre-initiated webdriver during the whole test session, instead of starting/stopping the webdriver for each test / module.
I think normally reusing a process is a bad idea, but Pyodide CI fails when starting a webdriver multiple times... so I guess this can be a workaround.
- Reference: https://www.selenium.dev/selenium/docs/api/py/webdriver_safari/selenium.webdriver.safari.webdriver.html#selenium.webdriver.safari.webdriver.WebDriver
- xref PR: https://github.com/pyodide/pyodide/pull/4270
> Add a fixture to reuse safari webdriver

- CHANGELOG.md
- pytest_pyodide/decorator.py
- tests/test_decorator.py
It still doesn't support *args or **kwargs arguments though.
> ENH run_in_pyodide type annotations, defaults, posonly, and kwonly args

- pytest_pyodide/node_test_driver.js
Needed to fix CI on https://github.com/pyodide/pyodide/pull/4282.
Maybe we should consider putting the entire node global scope in?
> ENH Add Headers to node scope

- CHANGELOG.md
- pytest_pyodide/doctest.py
- pytest_pyodide/fixture.py
- pytest_pyodide/hook.py
- pytest_pyodide/run_tests_inside_pyodide.py
- tests/test_doctest.py
- tests/test_options.py
If the first line of the doctest has `# doctest: +RUN_IN_PYODIDE`, then we will run it in Pyodide once for each runtime available.
> ENH Add support for running doctests in pyodide

- pyproject.toml
- pytest_pyodide/_decorator_in_pyodide.py
tblib 3.0 has been released with support for pickling frame locals:
https://github.com/ionelmc/python-tblib/issues/41
This PR attempts to use the new tblib 3.0 feature, with a fallback for older Pyodide versions
> Use new tblib 3.0 features

- CHANGELOG.md
- pytest_pyodide/_templates/module_webworker_dev.js
- pytest_pyodide/_templates/webworker_dev.js
- pytest_pyodide/server.py
Similar to #87, embed `module_webworker_dev.js` and `webworker_dev.js` files that are used in pytest-pyodide to test webworker functionality.  This is used in `run_webworker` method:
https://github.com/pyodide/pytest-pyodide/blob/bfa37e28050184795d2132f365ec83532ab8e4e5/pytest_pyodide/runner.py#L293-L302
I need this to run webworker tests with `pyodide-core` archive in https://github.com/ryanking13/pyodide-recipes-mirror
> Embed JS files for testing webworker into pytest-pyodide wheel

- CHANGELOG.md
- COMPATIBILITY.md
- pytest_pyodide/runner.py
This parameter has been removed from selenium 4.16
Related: https://github.com/pyodide/pyodide/pull/4333#issuecomment-1848081420
> Remove reuse_service parameter from safari webdriver constructor

- README.md
Based on the https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-workflow-file-name there is a need to link to the workflow name, but if the workflow hasn't run actions, it doesn't generate the bage - so moved it to build.yml
> sorry, finally fixing it - moving to the build.yml that is in actions

- pytest_pyodide/decorator.py
The `@run_in_pyodide` decorator shows up in pytest when verbosity is high.
```
$ pytest -v -v -v packages/sympy
============================================================== test session starts ==============================================================
platform linux -- Python 3.11.7, pytest-7.4.4, pluggy-1.4.0 -- /opt/conda/envs/pyodide-env/bin/python3.11
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/workspaces/pyodide/.hypothesis/examples'))
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /workspaces/pyodide
configfile: pyproject.toml
plugins: cov-4.1.0, hypothesis-6.97.0, …
```
> pytest_pyodide.decorator: Use functools.update_wrapper

- .github/workflows/build.yaml
- .github/workflows/main.yaml
- .github/workflows/testall.yaml
- CHANGELOG.md
- COMPATIBILITY.md
- pytest_pyodide/node_test_driver.js
- tests/test_decorator.py
- tests/test_js.py
- utils/build_test_matrix.py
Fixes node error in: https://github.com/pyodide/pyodide/pull/4846
Resolve #136.
I commented out refcount check in selenium_handle which seems failing after Python version update, and disabled playwright test temporarily, which has been keep getting timeout recently.
> Expose AbortController in node

- pytest_pyodide/__init__.py
- pytest_pyodide/node_test_driver.js
- pytest_pyodide/runner.py
This fixes issue #139 . It would be nice to get it merged so I can test node.js in urllib3
> split long lines of js input for node.js to avoid tty issues

- pytest_pyodide/doctest.py
IPython has a custom doctest runner and having pytest-pyodide installed make the test suite fails on this attribute.
> Don't assume test.pyodide_test always exists.

- pytest_pyodide/node_test_driver.js
Since node v20 we can pass `importModuleDynamically` to allow dynamic imports in code run by `vm.runInContext`. In older node versions, we fall back to the old behavior.
Tested manually.
> Allow dynamic imports in node selenium code

- conftest.py
- pytest_pyodide/config.py
- pytest_pyodide/node_test_driver.js
- pytest_pyodide/runner.py
- tests/test_js.py
So we can add additional global variables to the node jsglobals without changes to pytest-pyodide.
> Add node_extra_globals config

- pytest_pyodide/decorator.py
- pytest_pyodide/run_tests_inside_pyodide.py
- pytest_pyodide/runner.py
- pytest_pyodide/utils.py
This PR resolves the [`no-else-return / R1705`](https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/no-else-return.html) warning.
> Resolve pylint R1705

- pyproject.toml
- pytest_pyodide/decorator.py
This PR resolves the [`no-else-raise / R1720`](https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/no-else-raise.html) / [`superfluous-else-raise (RET506)`](https://docs.astral.sh/ruff/rules/superfluous-else-raise/#superfluous-else-raise-ret506) warning.
Similar to #170.
> Resolve pylint R1720

- pyproject.toml
This PR follows the [suggestion](https://github.com/pyodide/pytest-pyodide/pull/170#issuecomment-3120445319) of @hoodmane to introduce new lints into the config.
In short:
- #168 relates to [`boolean-chained-comparison (PLR1716)`](https://docs.astral.sh/ruff/rules/boolean-chained-comparison/)
- #170 relates to [`superfluous-else-return (RET505)`](https://docs.astral.sh/ruff/rules/superfluous-else-return/)
Note that the above rules have _automatic fix available_, so the [current config of pre-commit](https://github.com/pyodide/pytest-pyodide/blob/f1b67d1424fc0591979cb38ee2418279f2612d5c/.pre-commit-config.yaml#L22) will handle them and this change will not introduce an extra cost for the developers.
The remaining PRs:
- #166,
- #169,
do not relate to any ruff rule (at the moment).
> Add newly resolved lints

- pyproject.toml
- pytest_pyodide/hook.py
Resolves the [`useless-return / R1711`](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/useless-return.html) / [`useless-return (PLR1711)`](https://docs.astral.sh/ruff/rules/useless-return/) warning.
> Resolve pylint R1711
